name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.14.2
          register-url: https://npm.pkg.github.com/
          scope: '@tensingn'
      - run: cd ./package
      - run: npm install
      - run: npm run build
      - run: cd ./dist
      - run: npm publish
        env:
          NODE_AUTH_TOKE: ${{secrets.GITHUB_TOKEN}}
